# This file contains a plain list of directories (one per line) to be included in the PATH environment variable.
# It is not a shell script. Use a loader script in your shell configuration to process and export these paths.

~/bin
~/.cargo/bin
~/.go/bin
~/.local/bin
$HOME/.nix-profile/bin
/opt/homebrew/bin
/opt/homebrew/sbin